export const gamesWithCoopData = {
  "3011"
    : [
      {
        "PPID": "2352",
        "Name": "Age of Wonders: Planetfall",
        "Img": "https://image.api.playstation.com/vulcan/img/rnd/202010/0716/HTp4sg8nvqCdNoMJnufsqmO9.png",
        "OpenCriticID": "7408",
        "Difficulty": "5", "HoursLow": 50, "HoursHigh": 60, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:28", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "4995",
        "SalePrice": "1248",
        "PlusPrice": "1248",
        "formattedBasePrice": "€49.95",
        "formattedSalePrice": "€12.48",
        "formattedPlusPrice": "€12.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/2352-age-of-wonders-planetfall",
        "trimmedName": "Age of Wonders: Planetfall",
        "coopData":
          [
            {
              "id": ["8880"],
              "title": ["Age of Wonders: Planetfall"],
              "system": ["PlayStation 4"],
              "genre": ["Turn Based Strategy"],
              "publisher": ["Paradox Interactive"],
              "esrb": ["Teen"],
              "releasedate": ["2019-08-06"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["Stand Alone Scenarios and Random Maps can be played with up to 8 players which can be AI or Human Players. Theoretically you could setup a game with 7 human players VS 1 AI (though this would be unfair for the AI). Because of this we've listed co-op as 4 (for balance).You can play coop together on one machine in Hotseat or in online sessions with fixed teams. This is the local co-op aspect. Note The campaign is single player only."],
              "background": ["Emerge from the cosmic dark age of a fallen galactic empire to build a new future for your people. Age of Wonders: Planetfall is the new strategy game from Triumph Studios, creators of the critically acclaimed Age of Wonders series, bringing all the exciting tactical turn-based combat and in-depth empire building of its predecessors to space in an all-new, sci-fi setting.Build your empire with one of six unique factions, ranging from the militant Vanguard to the dinosaur-riding Amazons and the cyborg-zombies of the Assembly. Progress through each faction’s missions using your wits, military strength and diplomacy, exploring planetary ruins and encountering other survivors as you unravel the history of a shattered civilization. Fight, build, negotiate and technologically advance your way to utopia in a deep single player campaign, on random skirmish maps, and against friends in multiplayer."],
              "url": ["https://www.co-optimus.com/game/8880/PlayStation 4/age-of-wonders-planetfall.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8880.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8880.jpg"]
            }]
      },
      {
        "PPID": "643",
        "Name": "Battle Planet - Judgement Day",
        "Img": "https://image.api.playstation.com/vulcan/img/rnd/202108/1018/qmqEYnf81NjfzeCeomDYxkRU.png",
        "OpenCriticID": "8672",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:27", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "995",
        "SalePrice": "398",
        "PlusPrice": "398",
        "formattedBasePrice": "€9.95",
        "formattedSalePrice": "€3.98",
        "formattedPlusPrice": "€3.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/643-battle-planet-judgement-day",
        "trimmedName": "Battle Planet",
        "coopData":
          [
            {
              "id": ["5891"],
              "title": ["Battle Planet - Judgment Day"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["Wildriver Games"],
              "esrb": ["Teen"],
              "releasedate": ["2019-10-17"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Two player couch co-op is supported in the main game mode. Each player chooses their own character to play"],
              "background": ["They are all after you - behind the convict, who just managed to flee from an accidental transport ship. “All of them” means heavily armed police, soldiers, nasty aliens and deadly robots. Make your way through the approaching hordes, fight through violent explosions and blazing fire, and try not to go under in this endless orgy of brute force.From a bird's eye view, you can see the huge battlefield in which you are moving: the surface of whole planets, which turn in perspective with you. After fighting your way through one planet, the transport capsule will take you to the next one.Discover an entire galaxy of randomly generated new planets with different surfaces and conditions. Be sure to use the many upgrades that keep you on your way. Because you have only one goal - survival!"],
              "url": ["https://www.co-optimus.com/game/5891/PlayStation 4/battle-planet-judgment-day.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5891.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5891.jpg"]
            }]
      },
      {
        "PPID": "3390",
        "Name": "Black Paradox",
        "Img": "https://image.api.playstation.com/cdn/EP8925/CUSA15050_00/6jKmRlNsFWCNRdSQry9fXTIxfKjErJpx.png",
        "OpenCriticID": "7663",
        "Difficulty": "5", "HoursLow": 12, "HoursHigh": 18, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:29", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1495",
        "SalePrice": "448",
        "PlusPrice": "448",
        "formattedBasePrice": "€14.95",
        "formattedSalePrice": "€4.48",
        "formattedPlusPrice": "€4.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/3390-black-paradox",
        "trimmedName": "Black Paradox",
        "coopData":
          [
            {
              "id": ["5676"],
              "title": ["Black Paradox"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Digerati Distribution"],
              "esrb": ["Everyone"],
              "releasedate": ["2019-04-30"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Team up with a buddy on your couch to defeat the Hellraisers and save the galaxy"],
              "background": ["Black Paradox is a roguelite shoot 'em up. Unleash an arsenal of weapons, power-ups, drones, and other upgrades to survive waves of enemies against a backdrop of pixel art and synth-wave soundtrack. As the infamous bounty hunter Black Paradox, travel through space and defeat the most dangerous criminal organization in the galaxy: the Hellraisers and its seven lieutenants."],
              "url": ["https://www.co-optimus.com/game/5676/PlayStation 4/black-paradox.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5676.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5676.jpg"]
            }]
      },
      {
        "PPID": "249",
        "Name": "Contra Anniversary Collection",
        "Img": "https://image.api.playstation.com/cdn/EP0101/CUSA15488_00/j7jPPNZFYQkAG6tSgPesYpErbdUOy4Pj.png",
        "OpenCriticID": "7888",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:29", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1995",
        "SalePrice": "498",
        "PlusPrice": "498",
        "formattedBasePrice": "€19.95",
        "formattedSalePrice": "€4.98",
        "formattedPlusPrice": "€4.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/249-contra-anniversary-collection",
        "trimmedName": "Contra Anniversary",
        "coopData":
          [
            {
              "id": ["5701"],
              "title": ["Contra Anniversary Collection"],
              "system": ["PlayStation 4"],
              "genre": ["Action"],
              "publisher": ["Konami"],
              "esrb": ["Everyone 10+"],
              "releasedate": ["2019-06-11"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["With the exception of Operation C, all games in the Contra Anniversary Collection support two player couch co-op throughout their campaigns. Operation C is single-player only."],
              "background": ["The Contra Anniversary Collection contains 10 entries from the Contra series of games. The following titles are included in the collection:\tContra (arcade version)\tContra (NES version)\tContra (Famicom version)\tSuper Contra (arcade version)\tSuper C (U.S. NES)\tContra III: The Alien Wars (U.S. SNES)\tSuper Probotector Alien Wars (European SNES) - same\tOperation C (Game Boy)\tContra: Hard Corps (U.S. Sega Genesis)\tProbotector (European Mega Drive)The Contra Anniversary Collection also includes the \"The Declassified History of Contra,\" which provides additional information about the Contra series."],
              "url": ["https://www.co-optimus.com/game/5701/PlayStation 4/contra-anniversary-collection.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5701.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5701.jpg"]
            }]
      },
      {
        "PPID": "246",
        "Name": "Contra: Rogue Corps",
        "Img": "https://image.api.playstation.com/vulcan/img/cfn/11307U-DktwgMVLvMQvsqdp5vOWF1bZmhYyk2pluwqmnrLYcaSChvF3oDWc5AfBFqNEqYmIs9plt2rYigv_dn0xZetERK570.png",
        "OpenCriticID": "8268",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:28", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "3995",
        "SalePrice": "799",
        "PlusPrice": "799",
        "formattedBasePrice": "€39.95",
        "formattedSalePrice": "€7.99",
        "formattedPlusPrice": "€7.99",
        "PlatPricesURL": "https://platprices.com/en-fi/game/246-contra-rogue-corps",
        "trimmedName": "Contra: Rogue Corps",
        "coopData":
          [
            {
              "id": ["5770"],
              "title": ["CONTRA: ROGUE CORPS"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["Konami"],
              "esrb": ["Mature"],
              "releasedate": ["2019-09-24"],
              "local": ["4"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["1"],
              "featurelist": ["Campaign Co-Op, Co-Op Modes"],
              "coopexp": ["Play through the campaign with up to three other players online, or take on Expedition Missions with three players on your couch (you cannot play through the campaign locally). For couch co-op, all progress is saved for the host (i.e., Player 1) only."],
              "background": ["Two years after the Alien Wars had ended, a mysterious area called the Damned City arose from the grounds where the final battles took place. Ruthless Fiends roamed the area, bringing a world full of madness. In the midst of chaos, 5 scoundrels emerge...they are the ROGUE CORPS. They do not look anything like heroes of justice, but have they come to save humanity, or maybe they are looking to hit the jackpot by searching the Damned City for treasures...either way, the fate of the world is in their hands."],
              "url": ["https://www.co-optimus.com/game/5770/PlayStation 4/contra-rogue-corps.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5770.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5770.jpg"]
            }]
      },
      {
        "PPID": "64443",
        "Name": "Crimsonland",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202012/1813/WksIonbSriib1ddGJCZeEtC2.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:19", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "995",
        "SalePrice": "248",
        "PlusPrice": "248",
        "formattedBasePrice": "€9.95",
        "formattedSalePrice": "€2.48",
        "formattedPlusPrice": "€2.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/64443-crimsonland",
        "trimmedName": "Crimsonland",
        "coopData":
          [
            {
              "id": ["8447"],
              "title": ["Crimsonland"],
              "system": ["PlayStation 5"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2021-01-20"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["Players work together to stop swarms of enemies."],
              "background": ["It's invasion time as the player must defend himself against thousands of aliens that surround him. This objective is accomplished using a variety of weapons, perks and bonuses. Gameplay is similar to Robotron 2084."],
              "url": ["https://www.co-optimus.com/game/8447/PlayStation 5/crimsonland.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8447.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8447.jpg"]
            }]
      },
      {
        "PPID": "14522",
        "Name": "Crimsonland",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202012/1813/WksIonbSriib1ddGJCZeEtC2.png",
        "OpenCriticID": "237",
        "Difficulty": "10", "HoursLow": 25, "HoursHigh": 30, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:48", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "995",
        "SalePrice": "248",
        "PlusPrice": "248",
        "formattedBasePrice": "€9.95",
        "formattedSalePrice": "€2.48",
        "formattedPlusPrice": "€2.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/14522-crimsonland",
        "trimmedName": "Crimsonland",
        "coopData":
          [
            {
              "id": ["8446"],
              "title": ["Crimsonland"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2021-01-20"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["Players work together to stop swarms of enemies."],
              "background": ["It's invasion time as the player must defend himself against thousands of aliens that surround him. This objective is accomplished using a variety of weapons, perks and bonuses. Gameplay is similar to Robotron 2084."],
              "url": ["https://www.co-optimus.com/game/8446/PlayStation 4/crimsonland.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8446.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8446.jpg"]
            }]
      },
      {
        "PPID": "82377",
        "Name": "Deep Rock Galactic",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202111/2310/1FjFdcGWmeuOpjGpodm1XYOj.png",
        "OpenCriticID": "-1",
        "Difficulty": "5", "HoursLow": 500, "HoursHigh": 750, "IsPS4": "1", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:09", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "2995",
        "SalePrice": "1797",
        "PlusPrice": "1797",
        "formattedBasePrice": "€29.95",
        "formattedSalePrice": "€17.97",
        "formattedPlusPrice": "€17.97",
        "PlatPricesURL": "https://platprices.com/en-fi/game/82377-deep-rock-galactic",
        "trimmedName": "Deep Rock Galactic",
        "coopData":
          [
            {
              "id": ["10972"],
              "title": ["Deep Rock Galactic"],
              "system": ["PlayStation 5"],
              "genre": ["First Person Shooter"],
              "publisher": ["Coffee Stain Studios"],
              "esrb": ["Teen"],
              "releasedate": ["2022-01-04"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Join a team of up to 4 players to fight, dig and explore your way through enormous cave systems, uncover the greatest riches, and make it out alive"],
              "background": ["DEEP ROCK GALACTIC is a procedurally generated first person co-op shooter for up to 4 players, developed in Unreal Engine 4. As a team of veteran dwarven space miners, you must go on missions for your corporate overlords and venture into the deepest, most dangerous cave systems of the most hostile planet ever discovered.Experience teamwork as you’ve never experienced it in a co-op game before. Complete missions and gather ever more riches. Expand your roster of class-based skills, unlock new gear and weapons, and take on the worst monsters the galaxy has to offer."],
              "url": ["https://www.co-optimus.com/game/10972/PlayStation 5/deep-rock-galactic.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/10972.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.10972.jpg"]
            }]
      },
      {
        "PPID": "88228",
        "Name": "Dolmen",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202108/1214/jipfxj4c35WlZsPKFWv8GEXz.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:04", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "3995",
        "SalePrice": "2796",
        "PlusPrice": "2796",
        "formattedBasePrice": "€39.95",
        "formattedSalePrice": "€27.96",
        "formattedPlusPrice": "€27.96",
        "PlatPricesURL": "https://platprices.com/en-fi/game/88228-dolmen",
        "trimmedName": "Dolmen",
        "coopData":
          [
            {
              "id": ["11601"],
              "title": ["DOLMEN"],
              "system": ["PlayStation 5"],
              "genre": ["Action RPG"],
              "publisher": ["Prime Matter"],
              "esrb": ["Teen"],
              "releasedate": ["2022-05-20"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Drop-In/Drop-Out, Co-Op Modes"],
              "coopexp": ["The host can summon other players using Dolmen Crystals to assist in boss fights. Once the boss is defeated however, the guests are kicked. The kill is also only counted for the host."],
              "background": ["Set in a sci-fi universe where humanity has colonized several star systems using space travel, technology, and genetic manipulation to adapt to the conditions, Dolmen has players battling across a distant planet - Revion Prime - trying to unravel a mystery of alien species, corrupt corporations, and unknown dimensions.Behind everything appears to be an alien species called Vahani that roams the universe altering the genetic makeup of other species. However, it remains to be seen if their motives are noble or more malevolent. It’s suspected that a crystal called Dolmen is the key to their work, and planet Revion Prime has an abundance of it that you’ll need to collect in order to unravel a web of secrets."],
              "url": ["https://www.co-optimus.com/game/11601/PlayStation 5/dolmen.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/11601.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.11601.jpg"]
            }]
      },
      {
        "PPID": "1765",
        "Name": "Freakout: Calamity Tv Show",
        "Img": "https://image.api.playstation.com/vulcan/img/cfn/11307ktwhlAvWhdOWvFbD6jmFCAFcCZcU8GrNRXeWRC7aDycaEc9vZCHoHradbsbnDoh3yD1MWFVV6XxJwHYhtFG6sEB4hE8.png",
        "OpenCriticID": "-1",
        "Difficulty": "3", "HoursLow": 5, "HoursHigh": 6, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:24", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1095",
        "SalePrice": "273",
        "PlusPrice": "273",
        "formattedBasePrice": "€10.95",
        "formattedSalePrice": "€2.73",
        "formattedPlusPrice": "€2.73",
        "PlatPricesURL": "https://platprices.com/en-fi/game/1765-freakout-calamity-tv-show",
        "trimmedName": "Freakout: Calamity Tv Show",
        "coopData":
          [
            {
              "id": ["6050"],
              "title": ["Freakout: Calamity TV Show"],
              "system": ["PlayStation 4"], "steam": ["848430"],
              "genre": ["Action"],
              "publisher": ["JanduSoft"],
              "esrb": ["Teen"],
              "releasedate": ["2020-04-17"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Team up with a friend in couch co-op through the game's main mode."],
              "background": ["Freakout: Calamity TV Show is a juicy Top-Down-Dual-Stick-Shooter inspired by old school arcade games and more recent Die & Retry shooters.In a disturbed dystopia filled with mutants and killing machines, you’re the star of a reality show which might get a bit too real. Fight your way through the deadly enemy waves, join the revolution, and try to take down the evil Fizzy Corp. Features- Fast and Intense action will blow your mind!- Challenge your skills from homeopatic level of difficulty to ... overdose of enemies !- Crazy dialogues and characters, talented artist behind!- Killer Soundtrack, you cannot play without headbanging!- 2 Player Couch Coop to double the fun!- 19 Levels with varied gameplay, so close to 20!- 5 Chapters with badass Bossfights!- Beautiful 3D Graphics to display all 13 sexy enemy types !- Customize your gear with various weapons and hero modifiers !"],
              "url": ["https://www.co-optimus.com/game/6050/PlayStation 4/freakout-calamity-tv-show.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/6050.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.6050.jpg"]
            }]
      },
      {
        "PPID": "30782",
        "Name": "FullBlast",
        "Img": "https://image.api.playstation.com/cdn/EP0896/CUSA12344_00/8b7ij4HHeIuas8AY5ub8lkRF1l8g1whY.png",
        "OpenCriticID": "2184",
        "Difficulty": "1", "HoursLow": 0.5, "HoursHigh": 1, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:33", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "595",
        "SalePrice": "297",
        "PlusPrice": "297",
        "formattedBasePrice": "€5.95",
        "formattedSalePrice": "€2.97",
        "formattedPlusPrice": "€2.97",
        "PlatPricesURL": "https://platprices.com/en-fi/game/30782-fullblast",
        "trimmedName": "FullBlast",
        "coopData":
          [
            {
              "id": ["8967"],
              "title": ["FullBlast"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Ratalaika Games"],
              "esrb": ["Everyone 10+"],
              "releasedate": ["2018-09-04"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Drop-In/Drop-Out, Campaign Co-Op"],
              "coopexp": ["Two local players take control of ships and shoot things to their hearts' content."],
              "background": ["With an art style inspired by the 80’s and the 90’s, FullBlast is a vertical-scrolling shooter that will bring a dose of nostalgia to all gamers who spent many an hour at their local arcade, engaging in Shmups. But don’t worry, just because it’s retro in origin, modern conventions and technology have been considered, resulting in a modern and vibrant presentation that is the perfect way to introduce a new generation of gamers to a largely untapped genre. Across the game’s 12 random levels, humanity is on the verge of extinction due to an alien invasion and it just so happens, you're the last hope to save the world. So, get ready to take flight and let loose, because those aliens are not going to shoot themselves. Humanity’s retaliation starts here!"],
              "url": ["https://www.co-optimus.com/game/8967/PlayStation 4/fullblast.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8967.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8967.jpg"]
            }]
      },
      {
        "PPID": "7816",
        "Name": "Generation Zero",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202105/0408/sKRPuXpCw1HGFAV4GXKPG9Pv.png",
        "OpenCriticID": "7431",
        "Difficulty": "6", "HoursLow": 50, "HoursHigh": 75, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:30", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "2995",
        "SalePrice": "1048",
        "PlusPrice": "1048",
        "formattedBasePrice": "€29.95",
        "formattedSalePrice": "€10.48",
        "formattedPlusPrice": "€10.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/7816-generation-zero",
        "trimmedName": "Generation Zero",
        "coopData":
          [
            {
              "id": ["5148"],
              "title": ["Generation Zero"],
              "system": ["PlayStation 4"],
              "genre": ["First Person Shooter"],
              "publisher": ["Avalanche Software"],
              "esrb": ["Teen"],
              "releasedate": ["2019-03-26"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Team up with up to three of your friends in seamless co-op multiplayer. Collaborate and combine your unique skills to take down enemies, support downed friends by reviving them, and share the loot after an enemy is defeated."],
              "background": ["Welcome to 1980’s Sweden. The local population has gone missing, and machines of unknown origin roam the streets. Explore this vast open world to unravel the mystery of the invaders, perfect your fighting strategies and prepare to strike back. In Generation Zero, living is winning."],
              "url": ["https://www.co-optimus.com/game/5148/PlayStation 4/generation-zero.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5148.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5148.jpg"]
            }]
      },
      {
        "PPID": "29380",
        "Name": "In Space We Brawl",
        "Img": "https://image.api.playstation.com/cdn/EP4523/CUSA01257_00/8fJoIeyHWfDCdChPJx7muVwsMxyjuxJv.png",
        "OpenCriticID": "2403",
        "Difficulty": "3", "HoursLow": 16, "HoursHigh": 25, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:47", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "395",
        "SalePrice": "158",
        "PlusPrice": "158",
        "formattedBasePrice": "€3.95",
        "formattedSalePrice": "€1.58",
        "formattedPlusPrice": "€1.58",
        "PlatPricesURL": "https://platprices.com/en-fi/game/29380-in-space-we-brawl",
        "trimmedName": "In Space We Brawl",
        "coopData":
          [
            {
              "id": ["3565"],
              "title": ["In Space We Brawl"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Sony Computer Entertainment America"],
              "esrb": ["No Rating"],
              "releasedate": ["2014-10-14"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["0"],
              "featurelist": [""], "review": ["http://www.co-optimus.com/review/1451/page/1/in-space-we-brawl-co-op-review.html"],
              "coopexp": ["Comp stomp an AI team with a two-player team in a variety of arenas with a variety of ships and weapons."],
              "background": ["In Space We Brawl is a galactic twin stick shooter for up to 4 players. ItÃ¢ï¿½ï¿½s a local multiplayer game of skill, fun and competition. Find the spaceship that fits your play style and equip it with your favorite tool of destruction. There are more than 100 combinations to master!"],
              "url": ["https://www.co-optimus.com/game/3565/PlayStation 4/in-space-we-brawl.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/3565.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.3565.jpg"]
            }]
      },
      {
        "PPID": "14512",
        "Name": "Neon Chrome",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202010/1209/i3pUWy779wQaHQj2YkKvSarQ.png",
        "OpenCriticID": "2661",
        "Difficulty": "2", "HoursLow": 7.5, "HoursHigh": 10, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:43", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1495",
        "SalePrice": "448",
        "PlusPrice": "448",
        "formattedBasePrice": "€14.95",
        "formattedSalePrice": "€4.48",
        "formattedPlusPrice": "€4.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/14512-neon-chrome",
        "trimmedName": "Neon Chrome",
        "coopData":
          [
            {
              "id": ["4166"],
              "title": ["Neon Chrome"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2016-05-31"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["1"],
              "featurelist": ["Campaign Co-Op, Co-Op Modes"], "review": ["http://www.co-optimus.com/review/1852/page/1/neon-chrome-co-op-review.html"],
              "coopexp": ["Team up with up to four players locally to bring down the Overseer"],
              "background": ["Neon Chrome is a ruthless top-down cyberpunk shooter with rogue-like elements. The game takes place inside an arcology - a massive sci-fi mega structure.Blast your way through walls with guns and cybernetic abilities and try alternate approaches with different roles like the Assassin or the Cyber Psycho. Upgrade your character stats, discover new cybernetic enhancements and build up strength to finally face the Overseer. Every death is a new beginning - the path to defeating the Overseer is never the same.New co-op mode available in Paid DLC. Neon Chrome - Arena is an arena type survival game mode with leaderboards. Your goal is to survive as long as possible using any means necessary. Endless streams of enemies will eventually end your fight. Play single or as a couch co-op! How high can you score before your demise?"],
              "url": ["https://www.co-optimus.com/game/4166/PlayStation 4/neon-chrome.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/4166.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.4166.jpg"]
            }]
      },
      {
        "PPID": "64243",
        "Name": "Neon Chrome",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202012/1812/qPnsWqh4rhacUQoxfwkpIrW4.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "0", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:19", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1795",
        "SalePrice": "538",
        "PlusPrice": "538",
        "formattedBasePrice": "€17.95",
        "formattedSalePrice": "€5.38",
        "formattedPlusPrice": "€5.38",
        "PlatPricesURL": "https://platprices.com/en-fi/game/64243-neon-chrome",
        "trimmedName": "Neon Chrome",
        "coopData":
          [
            {
              "id": ["8337"],
              "title": ["Neon Chrome Overseer Edition"],
              "system": ["PlayStation 5"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2021-01-13"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Team up with up to four players locally to bring down the Overseer"],
              "background": ["Neon Chrome Overseer Edition takes advantage of the blazing fast next generation hardware to deliver even smoother gameplay, and includes Arena expansion!Neon Chrome is a ruthless top-down cyberpunk shooter with rogue-like elements. Blast your way through enemies and walls with guns and cybernetic abilities. Experiment with different roles like the Hacker or the Cyber Psycho. Upgrade your character stats, discover new cybernetic enhancements and build up strength. Every death is a new beginning - the path to stopping the Overseer is never the same.Neon Chrome - Arena is an arena type survival game mode with leaderboards. Your goal is to survive as long as possible using any means necessary. Play single or as local co-op! How high can you score before your demise?"],
              "url": ["https://www.co-optimus.com/game/8337/PlayStation 5/neon-chrome-overseer-edition.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8337.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8337.jpg"]
            }]
      },
      {
        "PPID": "1371",
        "Name": "Project Starship",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202203/2106/Iw3sbCCZAjQstGUkSOz1WLB1.png",
        "OpenCriticID": "-1",
        "Difficulty": "2", "HoursLow": 0.5, "HoursHigh": 1.2, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:25", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "495",
        "SalePrice": "198",
        "PlusPrice": "198",
        "formattedBasePrice": "€4.95",
        "formattedSalePrice": "€1.98",
        "formattedPlusPrice": "€1.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/1371-project-starship",
        "trimmedName": "Project Starship",
        "coopData":
          [
            {
              "id": ["8351"],
              "title": ["Project Starship X"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Eastasiasoft"],
              "esrb": ["Teen"],
              "releasedate": ["2021-01-27"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["A second player can join in and help blast away everything."],
              "background": ["Project Starship is back with a wacky take on cosmic horror. In this rogue-lite shooter, you’ll take the role of the tentacled-yet-hip Swagthulhu as you CRASH-KILL comical abominations in flashy 16-bit style! With multi-purpose dodge mechanics and tons of crazy pick-ups, you’ll be able to crash your ship straight through the enemy and emerge unscathed. Project Starship X celebrates genre conventions by turning them upside-down!"],
              "url": ["https://www.co-optimus.com/game/8351/PlayStation 4/project-starship-x.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8351.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8351.jpg"]
            }]
      },
      {
        "PPID": "64753",
        "Name": "Project Starship X",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202012/1609/SlytPv4moEXxUnxFpqzTmvW9.png",
        "OpenCriticID": "-1",
        "Difficulty": "3", "HoursLow": 0.5, "HoursHigh": 1, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:19", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "995",
        "SalePrice": "398",
        "PlusPrice": "398",
        "formattedBasePrice": "€9.95",
        "formattedSalePrice": "€3.98",
        "formattedPlusPrice": "€3.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/64753-project-starship-x",
        "trimmedName": "Project Starship X",
        "coopData":
          [
            {
              "id": ["8351"],
              "title": ["Project Starship X"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Eastasiasoft"],
              "esrb": ["Teen"],
              "releasedate": ["2021-01-27"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["A second player can join in and help blast away everything."],
              "background": ["Project Starship is back with a wacky take on cosmic horror. In this rogue-lite shooter, you’ll take the role of the tentacled-yet-hip Swagthulhu as you CRASH-KILL comical abominations in flashy 16-bit style! With multi-purpose dodge mechanics and tons of crazy pick-ups, you’ll be able to crash your ship straight through the enemy and emerge unscathed. Project Starship X celebrates genre conventions by turning them upside-down!"],
              "url": ["https://www.co-optimus.com/game/8351/PlayStation 4/project-starship-x.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8351.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8351.jpg"]
            }]
      },
      {
        "PPID": "3447",
        "Name": "Resogun",
        "Img": "https://image.api.playstation.com/cdn/EP9000/CUSA00005_00/kKAfWuugkNyJnmYlNumEKhN2kRjbYDCy.jpg",
        "OpenCriticID": "310",
        "Difficulty": "4", "HoursLow": 6, "HoursHigh": 10, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:49", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1295",
        "SalePrice": "647",
        "PlusPrice": "647",
        "formattedBasePrice": "€12.95",
        "formattedSalePrice": "€6.47",
        "formattedPlusPrice": "€6.47",
        "PlatPricesURL": "https://platprices.com/en-fi/game/3447-resogun",
        "trimmedName": "Resogun",
        "coopData":
          [
            {
              "id": ["3196"],
              "title": ["Resogun"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Sony Computer Entertainment America"],
              "esrb": ["Teen"],
              "releasedate": ["2013-11-15"],
              "local": ["2"],
              "online": ["2"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"], "review": ["http://www.co-optimus.com/review/1310/resogun-co-op-review.html"],
              "coopexp": ["Two players team up to complete levels for high scores. Three different ships are available."],
              "background": ["RESOGUN is a new exclusive PlayStation 4 shoot \\'em up from the same team that brought you Super Stardust HD, Super Stardust Delta and Dead Nation.Unleash an explosive array of devastating weapons to obliterate hordes of ruthless enemies while making sure you rescue the last survivors and keep your multiplier going!Experience the most intense destruction ever, as the power of PlayStationÂ®4 renders all enemies and levels using hundred of thousands of individual voxels that blow up in real time as you battle your way through.Push yourself to the limits trying to climb the global leaderboards for each game mode and difficulty setting.Join forces with your friends online and show off your skills in action packed co-op multiplayer."],
              "url": ["https://www.co-optimus.com/game/3196/PlayStation 4/resogun.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/3196.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.3196.jpg"]
            }]
      },
      {
        "PPID": "2642",
        "Name": "Rogue Stormers",
        "Img": "https://image.api.playstation.com/cdn/EP4402/CUSA06072_00/Cm9SoBPH8SEXbNtPdvQQ7exlFZx0vn1e.png",
        "OpenCriticID": "2627",
        "Difficulty": "8", "HoursLow": 18.8, "HoursHigh": 25, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:42", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1995",
        "SalePrice": "598",
        "PlusPrice": "398",
        "formattedBasePrice": "€19.95",
        "formattedSalePrice": "€5.98",
        "formattedPlusPrice": "€3.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/2642-rogue-stormers",
        "trimmedName": "Rogue Stormers",
        "coopData":
          [
            {
              "id": ["4622"],
              "title": ["Rogue Stormers"],
              "system": ["PlayStation 4"],
              "genre": ["Action"],
              "publisher": ["Black Forest Games"],
              "esrb": ["Teen"],
              "releasedate": ["2016-10-04"],
              "local": ["4"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Drop-In/Drop-Out, Campaign Co-Op"],
              "coopexp": ["Players team up and play through the levels combining powers and supporting each other to take down enemies."],
              "background": ["Rogue Stormers is slated to be a high-octane co-op carnage action-game, full of furious orcs armed with motor guns, rocket-propelled goblins and oodles of over-the-top craziness! In this side-scrolling platform shooter, up to four daredevils in petrol-powered armor will slam, blast and smash their way through a medieval oil rig city in the grip of chaos. Gameplay-wise, Rogue Stormers is gunning for a true co-op experience, with weapon choices, environment, enemies and positioning all blending together to dynamically create exciting situations that reward cooperative play. For example, repeatedly slamming that orc raider into a wall works just fine, but if you punt him to your buddy below, he'll blast the orc into the incinerator behind him and you can go to town on the goblins trying to ambush him from the skies."],
              "url": ["https://www.co-optimus.com/game/4622/PlayStation 4/rogue-stormers.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/4622.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.4622.jpg"]
            }]
      },
      {
        "PPID": "36692",
        "Name": "Söldner-X 2: Final Prototype - Definitive Edition",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202010/2015/gbAstdJnyJf3UrldMPbweoJB.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:21", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "995",
        "SalePrice": "398",
        "PlusPrice": "398",
        "formattedBasePrice": "€9.95",
        "formattedSalePrice": "€3.98",
        "formattedPlusPrice": "€3.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/36692-söldner-x-2-final-prototype-definitive-edition",
        "trimmedName": "Söldner-X 2: Final Prototype",
        "coopData":
          [
            {
              "id": ["8032"],
              "title": ["Söldner-X 2: Final Prototype Definitive Edition"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["East Asia Soft"],
              "esrb": ["Everyone"],
              "releasedate": ["2020-11-04"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Söldner-X 2: Final Prototype is a SHMUP all it's own allowing players to game together locally, share power-ups, and conquer the enormous bosses. Added challenges up the ante for those that are tired of the mundane, ready to take on the PSN leaderboards."],
              "background": ["A side-scrolling shooter sensation returns, bigger and bolder than ever before! Blending traditional arcade gameplay with scorching HD visuals and rocking audio presentation, Söldner-X 2: Definitive Edition is laser-focused on bringing everything the genre is known for into the current generation.Dynamic score-linked difficulty, a challenge mode that rewards skillful performance with bonus features, devastating limit attacks and a pumping soundtrack are just the beginning. All previous DLC is now included in the base game, replay sharing and online scoreboards support friend lists, weapon and boss effects have been updated, challenge difficulties have been rebalanced, plus there’s a new gallery mode. This is the ultimate realization of Söldner-X 2, fully revised and reborn!"],
              "url": ["https://www.co-optimus.com/game/8032/PlayStation 4/soldner-x-2-final-prototype-definitive-edition.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8032.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8032.jpg"]
            }]
      },
      {
        "PPID": "66415",
        "Name": "Spacebase Startopia",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202010/1912/WWI5h7S5t6QqEEiYJUwRLBmY.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:18", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "4995",
        "SalePrice": "1998",
        "PlusPrice": "1998",
        "formattedBasePrice": "€49.95",
        "formattedSalePrice": "€19.98",
        "formattedPlusPrice": "€19.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/66415-spacebase-startopia",
        "trimmedName": "Spacebase Startopia",
        "coopData":
          [
            {
              "id": ["8609"],
              "title": ["Spacebase Startopia"],
              "system": ["PlayStation 5"],
              "genre": ["Simulation"],
              "publisher": ["Kalypso Media"],
              "esrb": ["Everyone 10+"],
              "releasedate": ["2021-03-26"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["In cooperative multiplayer up to four players combine their efforts to manage the station and defend it against the invaders."],
              "background": ["Spacebase Startopia captivates with its original mixture of economic simulation and empire building strategy paired with classic RTS skirmishes and a good dose of humor. In addition to the challenging single player Campaign and the versatile battle mode, there are also competitive and cooperative multiplayer modes for up to four players. And as if maintaining the three Space Station Decks, entertaining the eight Alien races and defending against enemy invaders were not enough of a challenge, the dynamic narrator AI is not going to mince matters and commentates the events in a lovely but sharp-tongued manner."],
              "url": ["https://www.co-optimus.com/game/8609/PlayStation 5/spacebase-startopia.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8609.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8609.jpg"]
            }]
      },
      {
        "PPID": "66416",
        "Name": "Spacebase Startopia - Extended Edition",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202101/2511/LHeyCq3ib8UG5aFkEiELuHtr.png",
        "OpenCriticID": "-1",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "1", "LastDiscounted": "2022-06-29 07:33:18", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "5495",
        "SalePrice": "2198",
        "PlusPrice": "2198",
        "formattedBasePrice": "€54.95",
        "formattedSalePrice": "€21.98",
        "formattedPlusPrice": "€21.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/66416-spacebase-startopia-extended-edition",
        "trimmedName": "Spacebase Startopia",
        "coopData":
          [
            {
              "id": ["8609"],
              "title": ["Spacebase Startopia"],
              "system": ["PlayStation 5"],
              "genre": ["Simulation"],
              "publisher": ["Kalypso Media"],
              "esrb": ["Everyone 10+"],
              "releasedate": ["2021-03-26"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["In cooperative multiplayer up to four players combine their efforts to manage the station and defend it against the invaders."],
              "background": ["Spacebase Startopia captivates with its original mixture of economic simulation and empire building strategy paired with classic RTS skirmishes and a good dose of humor. In addition to the challenging single player Campaign and the versatile battle mode, there are also competitive and cooperative multiplayer modes for up to four players. And as if maintaining the three Space Station Decks, entertaining the eight Alien races and defending against enemy invaders were not enough of a challenge, the dynamic narrator AI is not going to mince matters and commentates the events in a lovely but sharp-tongued manner."],
              "url": ["https://www.co-optimus.com/game/8609/PlayStation 5/spacebase-startopia.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8609.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8609.jpg"]
            }]
      },
      {
        "PPID": "44",
        "Name": "Star Trek: Bridge Crew",
        "Img": "https://image.api.playstation.com/cdn/EP0001/CUSA05761_00/33aqzSZdVqO43EDU1WyRD8m1K1LtKgf3.png",
        "OpenCriticID": "3726",
        "Difficulty": "4", "HoursLow": 25, "HoursHigh": 30, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:38", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "2495",
        "SalePrice": "998",
        "PlusPrice": "998",
        "formattedBasePrice": "€24.95",
        "formattedSalePrice": "€9.98",
        "formattedPlusPrice": "€9.98",
        "PlatPricesURL": "https://platprices.com/en-fi/game/44-star-trek-bridge-crew",
        "trimmedName": "Star Trek: Bridge Crew",
        "coopData":
          [
            {
              "id": ["5116"],
              "title": ["Star Trek: Bridge Crew"],
              "system": ["PlayStation 4"],
              "genre": ["Simulation"],
              "publisher": ["Ubisoft"],
              "esrb": ["Everyone 10+"],
              "releasedate": ["2017-05-30"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["1"],
              "featurelist": ["Campaign Co-Op, Co-Op Modes"],
              "coopexp": ["In co-op, you can form a crew of four players to serve in the roles of Captain, Helm, Tactical and Engineer. In addition to a dynamic storyline, the game features an “Ongoing Missions” mode, procedurally generating missions for countless hours of Co-op adventure."],
              "background": ["Star Trek™: Bridge Crew, playable in both VR and non-VR, will immerse you in the Star Trek universe. The game puts you and your friends in the heart of the U.S.S. Aegis.Your mission: explore a largely uncharted sector of space known as The Trench, in hopes of locating a suitable new home world for the decimated Vulcan populace. The Klingon Empire is also active in the region, and their purpose is a threat to the Federation’s plans.NOTE: The PS4 version of Star Trek: Bridge crew supports PSVR."],
              "url": ["https://www.co-optimus.com/game/5116/PlayStation 4/star-trek-bridge-crew.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5116.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5116.jpg"]
            }]
      },
      {
        "PPID": "29301",
        "Name": "Super Destronaut DX",
        "Img": "https://image.api.playstation.com/cdn/EP0896/CUSA12554_00/SPVwTm4AHRrns2kfaMXhA0hnjIAe37MI.png",
        "OpenCriticID": "6371",
        "Difficulty": "2", "HoursLow": 0.7, "HoursHigh": 1.2, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:33", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "495",
        "SalePrice": "148",
        "PlusPrice": "148",
        "formattedBasePrice": "€4.95",
        "formattedSalePrice": "€1.48",
        "formattedPlusPrice": "€1.48",
        "PlatPricesURL": "https://platprices.com/en-fi/game/29301-super-destronaut-dx",
        "trimmedName": "Super Destronaut DX",
        "coopData":
          [
            {
              "id": ["5268"],
              "title": ["Super Destronaut DX"],
              "system": ["PlayStation 4"],
              "genre": ["Arcade"],
              "publisher": ["Ratalaika Games"],
              "esrb": ["Everyone"],
              "releasedate": ["2018-07-17"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["Team up with another player locally to fight off waves of alien attackers"],
              "background": ["Once upon a time, arcade shooter gamers where you have to fend off impending waves of an alien menace, was all the rage, but while retro may be old, it is never forgotten. So, inspired by an arcade classic, Super Destronaut DX is retro space shooter that pits you against an enemy more dreaded than a UFO, a scoreboard. With multiple modes and high-scores that can be attained by yourself and players all over the globe, this is a game that will put you on the path of achieving a score as high as you can possibly muster.So, if you are a fan of old-school shooters, be prepared to feel right at home and if you have a friend who is just as passionate as you are about shooting, why not have them play with you. With support for a local multiplayer mode, maybe the two of you together have just what it takes to beat the invading aliens once and for all and secure the top spot! You know you want too."],
              "url": ["https://www.co-optimus.com/game/5268/PlayStation 4/super-destronaut-dx.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5268.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5268.jpg"]
            }]
      },
      {
        "PPID": "3337",
        "Name": "Super Mutant Alien Assault",
        "Img": "https://image.api.playstation.com/cdn/EP8921/CUSA04874_00/EYCfHKyX7TtE2RMSKxrXKRZk90Vcgua3.png",
        "OpenCriticID": "3015",
        "Difficulty": "-1", "HoursLow": 7.5, "HoursHigh": 10, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:42", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1195",
        "SalePrice": "239",
        "PlusPrice": "239",
        "formattedBasePrice": "€11.95",
        "formattedSalePrice": "€2.39",
        "formattedPlusPrice": "€2.39",
        "PlatPricesURL": "https://platprices.com/en-fi/game/3337-super-mutant-alien-assault",
        "trimmedName": "Super Mutant Alien Assault",
        "coopData":
          [
            {
              "id": ["4248"],
              "title": ["Super Mutant Alien Assault"],
              "system": ["PlayStation 4"],
              "genre": ["Arcade"],
              "publisher": ["Surprise Attack Games"],
              "esrb": ["Teen"],
              "releasedate": ["2016-07-12"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["0"],
              "modes": ["0"],
              "featurelist": ["Drop-In/Drop-Out"],
              "coopexp": ["Local co-op for two living humans!"],
              "background": ["Super Mutant Alien Assault is a sci-fi, arena combat, action platformer game,about a ships robot that must fight off an alien assault. These aliens mutate when coming into contact with the ships radioactive fuel, turning already dangerous enemies into vicious monstrosities. Weapons and explosives are limited, and randomly dispensed by the ships weapon vending machines. With random weapons, and semi-random levels, skill is your only chance at survival."],
              "url": ["https://www.co-optimus.com/game/4248/PlayStation 4/super-mutant-alien-assault.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/4248.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.4248.jpg"]
            }]
      },
      {
        "PPID": "2649",
        "Name": "Tesla vs Lovecraft",
        "Img": "https://image.api.playstation.com/vulcan/ap/rnd/202011/2411/mCXLo2SCNrETXWAVYPHAMp8D.png",
        "OpenCriticID": "5419",
        "Difficulty": "4", "HoursLow": 10, "HoursHigh": 15, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:35", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1495",
        "SalePrice": "299",
        "PlusPrice": "299",
        "formattedBasePrice": "€14.95",
        "formattedSalePrice": "€2.99",
        "formattedPlusPrice": "€2.99",
        "PlatPricesURL": "https://platprices.com/en-fi/game/2649-tesla-vs-lovecraft",
        "trimmedName": "Tesla vs Lovecraft",
        "coopData":
          [
            {
              "id": ["4918"],
              "title": ["Tesla vs Lovecraft"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2018-03-13"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"], "review": ["http://www.co-optimus.com/review/2112/page/1/tesla-vs-lovecraft-co-op-review.html"],
              "coopexp": ["Blast monsters together in local co-op for 2-4 players"],
              "background": ["Tesla vs Lovecraft is an intense twin stick top-down shooter where the player, as Nikola Tesla, fights hordes of eldritch abomination minions of the horror author H.P. Lovecraft. The hallmark features of the game are the Quantum Teleport, which allows the player to warp a short distance even through walls and monsters, and the Tesla Mech battle robot, which the player is able to call down for immense boost in firepower. In genre tradition, a hefty arsenal of conventional and scifi weapons, powerups, special abilities, and selectable perks is also present."],
              "url": ["https://www.co-optimus.com/game/4918/PlayStation 4/tesla-vs-lovecraft.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/4918.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.4918.jpg"]
            },
            {
              "id": ["8074"],
              "title": ["Tesla Force"],
              "system": ["PlayStation 4"],
              "genre": ["Twin Stick Shooter"],
              "publisher": ["10tons Ltd"],
              "esrb": ["Teen"],
              "releasedate": ["2020-11-24"],
              "local": ["4"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Drop-In/Drop-Out, Campaign Co-Op"],
              "coopexp": ["The players take control of Tesla, Curie, Lovecraft or Shelley and fight their way in this Top-Down-Shooter through endless hordes of abominations."],
              "background": ["With science as your super power, charge up your coils and zap into action! Tesla Force is a rogue-lite top-down shooter featuring endless procedural gameplay with tentacle splitting action. Play as Tesla, Curie, Lovecraft and Shelley and blast the cosmic horror back into the galactic abyss!"],
              "url": ["https://www.co-optimus.com/game/8074/PlayStation 4/tesla-force.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/8074.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.8074.jpg"]
            }]
      },
      {
        "PPID": "25643",
        "Name": "Titanfall 2 - Ultimate Edition",
        "Img": "https://image.api.playstation.com/cdn/EP0006/CUSA04013_00/H4Ae7nxX1YVncbk5t0yoQYQ29QtAMzzF.png",
        "OpenCriticID": "2834",
        "Difficulty": "6", "HoursLow": 15, "HoursHigh": 25, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:38", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "2995",
        "SalePrice": "599",
        "PlusPrice": "599",
        "formattedBasePrice": "€29.95",
        "formattedSalePrice": "€5.99",
        "formattedPlusPrice": "€5.99",
        "PlatPricesURL": "https://platprices.com/en-fi/game/25643-titanfall-2-ultimate-edition",
        "trimmedName": "Titanfall 2",
        "coopData":
          [
            {
              "id": ["4702"],
              "title": ["Titanfall 2"],
              "system": ["PlayStation 4"],
              "genre": ["First Person Shooter"],
              "publisher": ["EA Redwood"],
              "esrb": ["Mature"],
              "releasedate": ["2016-10-28"],
              "local": ["0"],
              "online": ["4"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Co-Op Modes"],
              "coopexp": ["Co-op was added as post-launch DLC with the Frontier Defense Mode. Defend your Harvester against 5 waves of increasingly difficult enemies. Earn cash for defeating enemies that you can spend in between waves to purchase tools like Batteries, Arc Traps, Sentries, and more."],
              "background": ["Call down your Titan and get ready for an exhilarating first-person shooter experience in Titanfall 2! The sequel introduces a new single player campaign that explores the bond between Pilot and Titan. Or blast your way through an even more innovative and intense multiplayer experience - featuring 6 new Titans, deadly new Pilot abilities, expanded customization, new maps, modes, and much more. "],
              "url": ["https://www.co-optimus.com/game/4702/PlayStation 4/titanfall-2.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/4702.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.4702.jpg"]
            }]
      },
      {
        "PPID": "26982",
        "Name": "Twin Robots",
        "Img": "https://image.api.playstation.com/cdn/EP0896/CUSA06339_00/CYhp4beuCioYOSH3UxGGZ69mPGFNgWH1.png",
        "OpenCriticID": "-1",
        "Difficulty": "2", "HoursLow": 2, "HoursHigh": 4, "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:37", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "495",
        "SalePrice": "99",
        "PlusPrice": "99",
        "formattedBasePrice": "€4.95",
        "formattedSalePrice": "€0.99",
        "formattedPlusPrice": "€0.99",
        "PlatPricesURL": "https://platprices.com/en-fi/game/26982-twin-robots",
        "trimmedName": "Twin Robots",
        "coopData":
          [
            {
              "id": ["5059"],
              "title": ["Twin Robots"],
              "system": ["PlayStation 4"],
              "genre": ["Puzzle Platformer"],
              "publisher": ["Ratalaika Games"],
              "esrb": ["Everyone"],
              "releasedate": ["2017-10-03"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["0"],
              "campaign": ["1"],
              "modes": ["0"],
              "featurelist": ["Campaign Co-Op"],
              "coopexp": ["Two player couch co-op is fully supported, so as long as you have a friend to control the other robot, the only thing you'll need to focus on, is what your own robot is doing."],
              "background": ["Watt and Volt are two twin robots, who have been forgotten by time and abandoned in an old robot factory. Marked as defective by mistake, if they wish to prove themselves as deserving a place in today’s world, they must pass a series of grueling tests.You'll be running, jumping & solving puzzles together, but beware: Both robots are battery-powered so they consume energy in everything they do! Watch out for their battery levels! You can also transfer energy from one robot to the other so that both can safely reach the exit."],
              "url": ["https://www.co-optimus.com/game/5059/PlayStation 4/twin-robots.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5059.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5059.jpg"]
            }]
      },
      {
        "PPID": "3398",
        "Name": "XenoRaptor",
        "Img": "https://image.api.playstation.com/vulcan/img/cfn/11307ZfnzViwimfjPc94LzBy2KnFo1hNFQSMDG_8zOBGg68Y9UXdrzoNWlyiJcYxy4-9dQk4jo8lBJKH4l1h4n3H7VI7iMNH.png",
        "OpenCriticID": "8838",
        "Difficulty": "-1", "HoursLow": "-1", "HoursHigh": "-1", "IsPS4": "1", "IsPS5": "0", "LastDiscounted": "2022-06-29 07:33:26", "DiscountedUntil": "2022-07-13 22:59:00",
        "BasePrice": "1495",
        "SalePrice": "299",
        "PlusPrice": "224",
        "formattedBasePrice": "€14.95",
        "formattedSalePrice": "€2.99",
        "formattedPlusPrice": "€2.24",
        "PlatPricesURL": "https://platprices.com/en-fi/game/3398-xenoraptor",
        "trimmedName": "XenoRaptor",
        "coopData":
          [
            {
              "id": ["5937"],
              "title": ["XenoRaptor"],
              "system": ["PlayStation 4"],
              "genre": ["Shmup"],
              "publisher": ["Digerati Distribution"],
              "esrb": ["Everyone"],
              "releasedate": ["2019-12-17"],
              "local": ["2"],
              "online": ["0"],
              "lan": ["0"],
              "splitscreen": ["0"],
              "dropindropout": ["1"],
              "campaign": ["0"],
              "modes": ["1"],
              "featurelist": ["Drop-In/Drop-Out, Co-Op Modes"],
              "coopexp": ["Team up in missions designed for co-op play. Each player can use their own ship and customizations."],
              "background": ["XenoRaptor is a frantic and frenzied twin-stick shooter, pitting ridiculously armed space dragons against an interstellar armada. Strip your defeated foes of their parts to assemble the ultimate weapon. From evasive teleporting and defensive mines, to railguns, tractor beams, and mind control, XenoRaptor is bullet-hell action with countless tactical possibilities."],
              "url": ["https://www.co-optimus.com/game/5937/PlayStation 4/xenoraptor.html"],
              "art": ["https://www.co-optimus.com/cache/boxart/5937.jpg"],
              "thumbnail": ["https://www.co-optimus.com/cache/boxart/thumb.5937.jpg"]
            }]
      }]
}